dotfiles_dir = "Sync/repos/dotfiles"

[settings]

[settings.dots]
#bombadil = { source = "bombadil.toml", source = "bombadil.toml" }
bash = { source = ".bashrc", target = ".bashrc" }
alacritty = { source = "alacritty", target = ".config/alacritty" }
neovim = { source = "nvim", target = ".config/nvim" }
taskwarrior = { source = "taskwarrior", target = ".config/taskwarrior" }
starship = { source = "starship", target = ".config/"}
