github.com:
    users:
        zaphodb2002:
            oauth_token: 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
    git_protocol: https
    user: zaphodb2002
    oauth_token: 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
