github.com:
    users:
        zaphodb2002:
            oauth_token: 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
    git_protocol: https
    user: zaphodb2002
    oauth_token: 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
