format = """
[](green)\
$os\
$username\
$hostname\
[](green bg:yellow)\
$directory\
[](fg:yellow bg:red)\
$git_branch\
$git_status\
[](fg:red bg:blue)\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
[](fg:blue bg:cyan)\
$docker_context\
[](fg:cyan bg:purple)\
$time\
[ ](fg:purple)\
"""

palette = 'everforest-gsgvariant'

[palettes.everforest-gsgvariant]
green = "#a7c080"
yellow = "#dbbc7f"
red = "#e67e80"
blue = "#7fbbb3"
cyan = "#83c092"
purple = "#d699b6"
black = "#2d353b"


# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:green fg:black bold"
style_root = "bg:red fg:white bold"
format = '[$user ]($style)'
disabled = false

[hostname]
ssh_only = true
style = "bg:green fg:black bold"
#format = "@[$ssh_symbol$hostname] ($style) in "

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:green fg:black bold"
disabled = false # Disabled by default

[os.symbols]
#EndeavourOS = " "

[directory]
style = "bg:yellow fg:black"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "

[c]
symbol = " "
style = "bg:blue fg:black"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:cyan fg:black"
format = '[ $symbol $context ]($style) $path'

[elixir]
symbol = " "
style = "bg:blue fg:black"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:blue fg:black"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:red fg:black"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:red fg:black"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:blue fg:black"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bg:blue fg:black"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:blue fg:black"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:blue fg:black"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:blue fg:black"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:blue fg:black"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "󰆥 "
style = "bg:blue"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = "🦀"
style = "bg:blue fg:black bold"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:blue fg:black"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:purple fg:black bold"
format = '[ ♥ $time ]($style)'
