github.com:
    users:
        zaphodb2002:
            oauth_token: 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
    git_protocol: https
    user: zaphodb2002
    oauth_token: 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
