github.com:
    users:
        zaphodb2002:
            oauth_token: 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
    git_protocol: https
    user: zaphodb2002
    oauth_token: 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
