github.com:
    users:
        zaphodb2002:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: zaphodb2002
