github.com:
    users:
        zaphodb2002:
            oauth_token: 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
    git_protocol: https
    user: zaphodb2002
    oauth_token: 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
