github.com:
    users:
        zaphodb2002:
            oauth_token: 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
    git_protocol: https
    user: zaphodb2002
    oauth_token: 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
