github.com:
    users:
        zaphodb2002:
            oauth_token: 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
    git_protocol: https
    user: zaphodb2002
    oauth_token: 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
