github.com:
    users:
        zaphodb2002:
            oauth_token: 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
    git_protocol: https
    user: zaphodb2002
    oauth_token: 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
