github.com:
    users:
        zaphodb2002:
            oauth_token: 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
    git_protocol: https
    user: zaphodb2002
    oauth_token: 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
