github.com:
    users:
        zaphodb2002:
            oauth_token: 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
    git_protocol: https
    user: zaphodb2002
    oauth_token: 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
